### ISSUE TITLE
Create OSO Reddit Account and SubReddit

### ISSUE THREAD

**Issue by KeithSSmith** [open-science-org/admin#3]
To help with project outreach, communication, organization, and general awareness we should create a SubReddit and perhaps a subsequent account that allows us to help develop the community and drive conversation.

I think we should also consider creating a 2nd subreddit when we release a token/coin to ensure that we keep trading discussions away from platform and research topics.

Once the official subreddit is created we need to update the website.

**Comment by himalayajung** [comment]
Official subreddit of OSO project lives here https://www.reddit.com/r/openscienceorg/. Make sure to utilize it the maximum!
